# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node

name: Node-React.js CI

on:
  push:
    branches: [ mazhar-todo-test ] #branch to work with
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Node version to be used 14.x
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
